// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveFolder(arg1) {
  return window['go']['backend']['App']['ArchiveFolder'](arg1);
}

export function AuthorizeDrive() {
  return window['go']['backend']['App']['AuthorizeDrive']();
}

export function BringToFront() {
  return window['go']['backend']['App']['BringToFront']();
}

export function CancelLoginDrive() {
  return window['go']['backend']['App']['CancelLoginDrive']();
}

export function CheckDriveConnection() {
  return window['go']['backend']['App']['CheckDriveConnection']();
}

export function CheckFileExists(arg1) {
  return window['go']['backend']['App']['CheckFileExists'](arg1);
}

export function CheckFileModified(arg1, arg2) {
  return window['go']['backend']['App']['CheckFileModified'](arg1, arg2);
}

export function Console(arg1, arg2) {
  return window['go']['backend']['App']['Console'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['backend']['App']['CreateFolder'](arg1);
}

export function DeleteArchivedFolder(arg1) {
  return window['go']['backend']['App']['DeleteArchivedFolder'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['backend']['App']['DeleteFolder'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['backend']['App']['DeleteNote'](arg1);
}

export function DestroyApp() {
  return window['go']['backend']['App']['DestroyApp']();
}

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function GetAppVersion() {
  return window['go']['backend']['App']['GetAppVersion']();
}

export function GetArchivedTopLevelOrder() {
  return window['go']['backend']['App']['GetArchivedTopLevelOrder']();
}

export function GetModifiedTime(arg1) {
  return window['go']['backend']['App']['GetModifiedTime'](arg1);
}

export function GetTopLevelOrder() {
  return window['go']['backend']['App']['GetTopLevelOrder']();
}

export function InitializeDrive() {
  return window['go']['backend']['App']['InitializeDrive']();
}

export function ListFolders() {
  return window['go']['backend']['App']['ListFolders']();
}

export function ListNotes() {
  return window['go']['backend']['App']['ListNotes']();
}

export function LoadArchivedNote(arg1) {
  return window['go']['backend']['App']['LoadArchivedNote'](arg1);
}

export function LoadFileNotes() {
  return window['go']['backend']['App']['LoadFileNotes']();
}

export function LoadNote(arg1) {
  return window['go']['backend']['App']['LoadNote'](arg1);
}

export function LoadSettings() {
  return window['go']['backend']['App']['LoadSettings']();
}

export function LogoutDrive() {
  return window['go']['backend']['App']['LogoutDrive']();
}

export function MoveNoteToFolder(arg1, arg2) {
  return window['go']['backend']['App']['MoveNoteToFolder'](arg1, arg2);
}

export function NotifyFrontendReady() {
  return window['go']['backend']['App']['NotifyFrontendReady']();
}

export function OpenAppFolder() {
  return window['go']['backend']['App']['OpenAppFolder']();
}

export function OpenFile(arg1) {
  return window['go']['backend']['App']['OpenFile'](arg1);
}

export function OpenFileFromExternal(arg1) {
  return window['go']['backend']['App']['OpenFileFromExternal'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['backend']['App']['OpenURL'](arg1);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['backend']['App']['RenameFolder'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileNotes(arg1) {
  return window['go']['backend']['App']['SaveFileNotes'](arg1);
}

export function SaveNote(arg1, arg2) {
  return window['go']['backend']['App']['SaveNote'](arg1, arg2);
}

export function SaveNoteList() {
  return window['go']['backend']['App']['SaveNoteList']();
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function SaveWindowState(arg1) {
  return window['go']['backend']['App']['SaveWindowState'](arg1);
}

export function SelectFile() {
  return window['go']['backend']['App']['SelectFile']();
}

export function SelectSaveFileUri(arg1, arg2) {
  return window['go']['backend']['App']['SelectSaveFileUri'](arg1, arg2);
}

export function SyncNow() {
  return window['go']['backend']['App']['SyncNow']();
}

export function UnarchiveFolder(arg1) {
  return window['go']['backend']['App']['UnarchiveFolder'](arg1);
}

export function UpdateArchivedTopLevelOrder(arg1) {
  return window['go']['backend']['App']['UpdateArchivedTopLevelOrder'](arg1);
}

export function UpdateNoteOrder(arg1, arg2) {
  return window['go']['backend']['App']['UpdateNoteOrder'](arg1, arg2);
}

export function UpdateTopLevelOrder(arg1) {
  return window['go']['backend']['App']['UpdateTopLevelOrder'](arg1);
}
