// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeDrive() {
  return window['go']['backend']['App']['AuthorizeDrive']();
}

export function BringToFront() {
  return window['go']['backend']['App']['BringToFront']();
}

export function CancelLoginDrive() {
  return window['go']['backend']['App']['CancelLoginDrive']();
}

export function CheckDriveConnection() {
  return window['go']['backend']['App']['CheckDriveConnection']();
}

export function DeleteNote(arg1) {
  return window['go']['backend']['App']['DeleteNote'](arg1);
}

export function DeleteNoteDrive(arg1) {
  return window['go']['backend']['App']['DeleteNoteDrive'](arg1);
}

export function DestroyApp() {
  return window['go']['backend']['App']['DestroyApp']();
}

export function InitializeDrive() {
  return window['go']['backend']['App']['InitializeDrive']();
}

export function ListNotes() {
  return window['go']['backend']['App']['ListNotes']();
}

export function LoadArchivedNote(arg1) {
  return window['go']['backend']['App']['LoadArchivedNote'](arg1);
}

export function LoadNote(arg1) {
  return window['go']['backend']['App']['LoadNote'](arg1);
}

export function LoadSettings() {
  return window['go']['backend']['App']['LoadSettings']();
}

export function LogoutDrive() {
  return window['go']['backend']['App']['LogoutDrive']();
}

export function NotifyFrontendReady() {
  return window['go']['backend']['App']['NotifyFrontendReady']();
}

export function OpenFile(arg1) {
  return window['go']['backend']['App']['OpenFile'](arg1);
}

export function OpenFileFromExternal(arg1) {
  return window['go']['backend']['App']['OpenFileFromExternal'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['backend']['App']['SaveFile'](arg1, arg2);
}

export function SaveNote(arg1) {
  return window['go']['backend']['App']['SaveNote'](arg1);
}

export function SaveNoteList() {
  return window['go']['backend']['App']['SaveNoteList']();
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}

export function SaveWindowState(arg1) {
  return window['go']['backend']['App']['SaveWindowState'](arg1);
}

export function SelectFile() {
  return window['go']['backend']['App']['SelectFile']();
}

export function SelectSaveFileUri(arg1, arg2) {
  return window['go']['backend']['App']['SelectSaveFileUri'](arg1, arg2);
}

export function SyncNotes() {
  return window['go']['backend']['App']['SyncNotes']();
}

export function SyncNow() {
  return window['go']['backend']['App']['SyncNow']();
}

export function UpdateNoteOrder(arg1, arg2) {
  return window['go']['backend']['App']['UpdateNoteOrder'](arg1, arg2);
}

export function UploadNote(arg1) {
  return window['go']['backend']['App']['UploadNote'](arg1);
}
