// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteNote(arg1:string):Promise<void>;

export function DestroyApp():Promise<void>;

export function ListNotes():Promise<Array<main.Note>>;

export function LoadArchivedNote(arg1:string):Promise<main.Note>;

export function LoadNote(arg1:string):Promise<main.Note>;

export function LoadSettings():Promise<main.Settings>;

export function OpenFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveNote(arg1:main.Note):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectSaveFileUri(arg1:string,arg2:string):Promise<string>;
