// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthorizeDrive() {
  return window['go']['main']['App']['AuthorizeDrive']();
}

export function CompleteAuth(arg1) {
  return window['go']['main']['App']['CompleteAuth'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteNoteDrive(arg1) {
  return window['go']['main']['App']['DeleteNoteDrive'](arg1);
}

export function DestroyApp() {
  return window['go']['main']['App']['DestroyApp']();
}

export function InitializeDrive() {
  return window['go']['main']['App']['InitializeDrive']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function LoadArchivedNote(arg1) {
  return window['go']['main']['App']['LoadArchivedNote'](arg1);
}

export function LoadNote(arg1) {
  return window['go']['main']['App']['LoadNote'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LogoutDrive() {
  return window['go']['main']['App']['LogoutDrive']();
}

export function NotifyFrontendReady() {
  return window['go']['main']['App']['NotifyFrontendReady']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SaveNoteList() {
  return window['go']['main']['App']['SaveNoteList']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWindowState(arg1) {
  return window['go']['main']['App']['SaveWindowState'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveFileUri(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveFileUri'](arg1, arg2);
}

export function SyncNotes() {
  return window['go']['main']['App']['SyncNotes']();
}

export function UpdateNoteOrder(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteOrder'](arg1, arg2);
}

export function UploadNote(arg1) {
  return window['go']['main']['App']['UploadNote'](arg1);
}
